Resolve RPM conflicts on Fedora > 23
e.g. on Fedora 25:

Error: Transaction check error:
  file /usr/share/man from install of somake-0.6.0-1.x86_64 conflicts with file from package filesystem-3.2-37.fc24.x86_64
  file /usr/share/man/man1 from install of somake-0.6.0-1.x86_64 conflicts with file from package filesystem-3.2-37.fc24.x86_64